# Generated by Django 4.2.7 on 2023-11-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='costumer',
            new_name='customer',
        ),
    ]
